[package]
name = "coffeegrounds-core"
version = "0.1.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
nom = "5.1.2"
enum-primitive-derive = "0.2.1"
num-traits = "0.2.12"
byteorder = "1.3.4"

thiserror = "1.0.20"
enumflags2 = "0.6.4"
smallvec = "1.4.2"
